---
all:
  children:
    proxmox_guests:
      children:
        proxmox_debian_guests:
          hosts:
            proxmox-pbs-0:
              ansible_host: 10.0.40.16
              ansible_user: root
              guest_kind: lxc

        proxmox_backup_servers:
          hosts:
            proxmox-pbs-0:

