---
docker_service_name: docker-svc-0
docker_service_root: /opt/{{ docker_service_name }}
docker_service_compose_file: "{{ docker_service_root }}/docker-compose.yml"
docker_service_env_file: "{{ docker_service_root }}/.env"
docker_service_runtime_dir: "{{ docker_service_root }}/run/tailscale"
docker_service_state_dir: "{{ docker_service_root }}/state/tailscale"
docker_service_technitium_data_dir: "{{ docker_service_root }}/data/technitium"
docker_service_technitium_log_dir: "{{ docker_service_root }}/logs/technitium"

docker_service_tailscale_ssh: true
docker_service_tailscale_advertise_routes:
  - "10.0.0.0/16"
  - "192.168.0.0/16"

