---
tailscale_authkey: "{{ lookup('ansible.builtin.env', 'TAILSCALE_AUTHKEY') }}"
tailscale_ssh: true
tailscale_accept_dns: false
tailscale_accept_routes: false
tailscale_advertise_exit_node: true
tailscale_advertise_routes:
  - "10.0.0.0/16"
  - "192.168.0.0/16"
tailscale_advertise_tags: "tag:container"
