---
komodo_root: /opt/komodo
komodo_config_root: /etc/komodo
komodo_hostname: komodo.koala-dominant.ts.net
komodo_port: 9120
komodo_image_tag: "2"
komodo_title: Komodo
komodo_timezone: Europe/London
komodo_database_username: admin
komodo_initial_admin_username: admin
komodo_disable_user_registration: true
komodo_resource_sync_name: home-dc-service-hosts
komodo_resource_sync_repo: fabricesemti80/home-dc-service-hosts
komodo_resource_sync_branch: main
komodo_resource_sync_paths:
  - komodo/resources.toml
komodo_run_resource_sync: true
komodo_managed_server_name: "{{ inventory_hostname }}"
komodo_env_variables:
  - name: TAILSCALE_OAUTH_CLIENT_ID
  - name: TAILSCALE_OAUTH_CLIENT_SECRET
    secret: true
  - name: TECHNITIUM_ADMIN_PASSWORD
    secret: true
  - name: TECHNITIUM_NODE0_TOKEN
    secret: true
  - name: TECHNITIUM_NODE1_TOKEN
    secret: true
  - name: TECHNITIUM_NODE2_TOKEN
    secret: true
  - name: KESTRA_HOSTNAME
    required: true
  - name: KESTRA_BASIC_AUTH_USERNAME
    required: true
  - name: KESTRA_BASIC_AUTH_PASSWORD
    secret: true
    required: true
  - name: KESTRA_POSTGRES_PASSWORD
    secret: true
    required: true
  - name: KESTRA_SSH_PRIVATE_KEY_PATH
    required: true
